### ISSUE TITLE
Snippet don't seem to trigger

### ISSUE THREAD

**Issue by simoneb** [fastify/fastify-snippet#4]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

-

### Plugin version

-

### Node.js version

-

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

I was asked to try this out by @mcollina and I can't seem to be able to trigger the snippets. When typing the shortcuts in the editor or using the "insert snippet" menu in VS code doesn't seem to show any of the snippets, even after a restart of VS code after installing the extension.

### Steps to Reproduce

-

**Comment by climba03003** [comment]
I think the reason is `package.json` is linked to the wrong path.
https://github.com/fastify/fastify-snippet/blob/main/package.json#L24
It should be in `./snippets/snippets-js.json`

**Comment by Eomm** [comment]
Thanks!

Checkout here
https://github.com/fastify/fastify-snippet/pull/3
so I will publish the fix

Note that in the project there is a `launch.json` to try it locally.. unfortunately I saw that the extensions are disabled but the global snippets are not! So I didn't spot it, I should add a better contributing section\

PS: I wrote to Microsoft support because I can't invite anyone as publisher

![image](https://user-images.githubusercontent.com/11404065/119564521-2c94bd00-bda9-11eb-9aca-059044093d5e.png)

**Comment by Eomm** [comment]
Released 1.0.1

@simoneb pleas take a look

**Comment by climba03003** [comment]
Working as expected.
![image](https://user-images.githubusercontent.com/23028015/119607997-d4e96680-be27-11eb-90a0-6609ef727c4d.png)
